### ISSUE TITLE
Output Model Weights, Graph Files

### ISSUE THREAD

**Issue by Jordan-Pierce** [coralnet/coralnet#481]
Hi @StephenChan,

Just curious to see if there would be a way to obtain the weights / graph files of a trained model for offline use?

Thanks,

Jordan

**Comment by StephenChan** [comment]
Hi Jordan - no there currently isn't.

The download of the trained model (classifier) itself is certainly feasible, as it's a pickled `CalibratedClassifierCV` on the order of 5-10 MB large (about the same as a typical image). So far we've been able to make the unpickling work across different scikit-learn versions.

One wrinkle off the top of my head: I'm not sure how strictly the image-features format (the input into `predict_proba()`) needs to match CoralNet's in order to get meaningful results from the classifiers. If it's too strict, then maybe one has to get our [pyspacer](https://github.com/beijbom/pyspacer/) module up and running to meaningfully use the downloaded classifiers, at which point you'd be able to train your own classifiers offline anyway.

But either way, I think it wouldn't hurt to implement this sometime. We've been looking into providing more info/transparency about previous-best classifiers and classifier details in general, which may include each individual classifier getting its own details page. Model downloads would fit well with that idea.

**Comment by Jordan-Pierce** [comment]
Oh, so at what point in the model pipeline are you using Scikit-Learn? I thought y'all switched over to EfficientNetB0? Or, do you have a fine-tuned (on coral images) EfficientNetB0 encoder, and just use it as a feature extractor, which outputs into an individual Scikit-Learn model for each source?

Regardless, yeah having the pre-processing code for input images would be necessary otherwise the results of the model would be garbage. Some deep learning frameworks do allow you to have layers that perform pre-processing within the actual model architecture, so you might be able to package everything together?

I just bring it up because, the API is super useful (I'm working on creating a GUI and .exe, see below), but if a project had computation resources to perform inference themselves, but wanted to continue using the model trained on CoralNet, it might be useful for downstream tasks that require faster inference, or no access to internet.


![Gooey_3](https://github.com/beijbom/coralnet/assets/115024024/0b04ccae-ecb3-4d58-9420-7267c444245b)

![Gooey_4](https://github.com/beijbom/coralnet/assets/115024024/2f613de9-64b4-4e7c-b182-48ad6655ba27)

**Comment by kriegman** [comment]
Specifically, Coralnet  uses the EfficientNet architecture, but the network
was trained on Benthic images. For the patch surrounding an image point,
the network is used to compute a feature vector, which is then classified
using a linear classifier or multilayer perceptron (scikitlearn). The
EfficientNet feature extractor is used across all CoralNet sources. The
classifier is trained (and retrained) for each source. As more images are
labelled/confirmed, the classifier is retrained.

While we save the classifier on CoralNet, we have not created a way to
export the classifier or use the weights outside of CoralNet and the API.

David

**Comment by StephenChan** [comment]
Nice GUI! Interesting to see how folks are getting the most out of the API.

For what it's worth - in our pipeline, inference on features is a fair bit faster than feature extraction. ~5 times faster at least, as a back of the envelope number.
